### ISSUE TITLE
EU Project Descriptions

### ISSUE THREAD

**Issue by JensLehmann** [LinkedDataStack/stack.linkeddata.org#1]
http://stack.linkeddata.org/eu-projects/ is empty.

**Comment by JensLehmann** [comment]
We should also generalise this to arbitrary projects (we also have national projects and there can also be non-research projects supporting the stack).

Generally, a distinction might be useful there:
- stack developers: mention LOD2, GeoKnow, Big Data Europe as projects; InfAI as organisation; Ontos as company
- stack sponsors: add InfAI, Ontos, Ten Force for now
- stack users: add the different use cases

This way, we could make that a more interesting "community" section in the website rather than just a project list.

**Comment by alegrm** [comment]
I've added to left menu links to Sponsors and Projects.. 
I think we cannot add all developers, thats quite a lot of maintenance. However for each component the develpers can add their link to their website (in the control file of the debian) and this is automatically added as website in http://stack.linkeddata.org/components/debian-repository/
